config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index", as: :welcome

  resources :home, only:[:index]
  resources :topics
  
  namespace :admins do 
    resources :home, only:[:index]
    resources :topics
    root to: "home#index"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_one :user

  def disply_status
    {"0" => "未审核", "1" => "审核不通过"}["#{status}"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  scope :day_count, ->{where("created_at between ? and ? ", Time.now.beginning_of_day, Time.now.end_of_day)}
  scope :month_count, ->{where("created_at between ? and ? ", Time.now.beginning_of_month, Time.now.end_of_day)}
  scope :year_count, ->{where("created_at between ? and ? ", Time.now.beginning_of_year, Time.now.end_of_day)}
end

app/controllers/admin_controller.rb
class AdminController <  ActionController::Base
  layout "admin"
  before_action :authenticate_admin!
  
end

app/controllers/admins/home_controller.rb
class Admins::HomeController < AdminController
  def index
    @day_count = User.day_count.count
    @month_count = User.month_count.count
    @year_count = User.year_count.count
    @all_count = User.all.count
  end

end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
  layout "admin"  

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  def after_sign_in_path_for(resource)
    admins_home_index_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_admin_session_path
  end


  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/topics_controller.rb
class Admins::TopicsController < AdminController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:user_id, :company_link, :content, :String, :title, :tag, :String)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:user_id, :company_link, :content, :String, :title, :tag, :String)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/admins/home/index.html.erb
<div class="container-fluid">
  <div class="animated fadeIn">
    <div class="row">
        <div class="col-sm-6 col-lg-3">
          <div class="card text-white bg-primary">
            <div class="card-body pb-0">
              <h4 class="mb-0"><%=@day_count%></h4>
              <p>当天注册人数</p>
            </div>
            <div class="chart-wrapper px-3" style="height:70px;">
              <canvas id="card-chart1" class="chart" height="70"></canvas>
            </div>
          </div>
        </div>
        <!--/.col-->
        <div class="col-sm-6 col-lg-3">
          <div class="card text-white bg-info">
            <div class="card-body pb-0">
              <h4 class="mb-0"><%=@month_count%></h4>
              <p>本月注册人数</p>
            </div>
            <div class="chart-wrapper px-3" style="height:70px;">
              <canvas id="card-chart2" class="chart" height="70"></canvas>
            </div>
          </div>
        </div>
        <!--/.col-->
        <div class="col-sm-6 col-lg-3">
          <div class="card text-white bg-warning">
            <div class="card-body pb-0">
              <h4 class="mb-0"><%=@year_count%></h4>
              <p>本年度注册人数</p>
            </div>
            <div class="chart-wrapper" style="height:70px;">
              <canvas id="card-chart3" class="chart" height="70"></canvas>
            </div>
          </div>
        </div>
        <!--/.col-->
        <div class="col-sm-6 col-lg-3">
          <div class="card text-white bg-danger">
            <div class="card-body pb-0">
              <h4 class="mb-0"><%=@all_count%></h4>
              <p>总注册人数</p>
            </div>
            <div class="chart-wrapper px-3" style="height:70px;">
              <canvas id="card-chart4" class="chart" height="70"></canvas>
            </div>
          </div>
        </div>
        <!--/.col-->
    </div>
    <!--/.row-->
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">Traffic</h4>
                    <div class="small text-muted">November 2015</div>
                </div>
                <!--/.col-->
                <div class="col-sm-7 hidden-sm-down">
                    <button type="button" class="btn btn-primary float-right"><i class="icon-cloud-download"></i>
                    </button>
                    <div class="btn-toolbar float-right" role="toolbar" aria-label="Toolbar with button groups">
                        <div class="btn-group mr-3" data-toggle="buttons" aria-label="First group">
                            <label class="btn btn-outline-secondary">
                                <input type="radio" name="options" id="option1">Day
                            </label>
                            <label class="btn btn-outline-secondary active">
                                <input type="radio" name="options" id="option2" checked="">Month
                            </label>
                            <label class="btn btn-outline-secondary">
                                <input type="radio" name="options" id="option3">Year
                            </label>
                        </div>
                    </div>
                </div>
                <!--/.col-->
            </div>
            <!--/.row-->
            <div class="chart-wrapper" style="height:300px;margin-top:40px;">
                <canvas id="main-chart" class="chart" height="300"></canvas>
            </div>
        </div>
        <div class="card-footer">
            <ul>
                <li>
                    <div class="text-muted">Visits</div>
                    <strong>29.703 Users (40%)</strong>
                    <div class="progress progress-xs mt-2">
                        <div class="progress-bar bg-success" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </li>
                <li class="hidden-sm-down">
                    <div class="text-muted">Unique</div>
                    <strong>24.093 Users (20%)</strong>
                    <div class="progress progress-xs mt-2">
                        <div class="progress-bar bg-info" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </li>
                <li>
                    <div class="text-muted">Pageviews</div>
                    <strong>78.706 Views (60%)</strong>
                    <div class="progress progress-xs mt-2">
                        <div class="progress-bar bg-warning" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </li>
                <li class="hidden-sm-down">
                    <div class="text-muted">New Users</div>
                    <strong>22.123 Users (80%)</strong>
                    <div class="progress progress-xs mt-2">
                        <div class="progress-bar bg-danger" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </li>
                <li class="hidden-sm-down">
                    <div class="text-muted">Bounce Rate</div>
                    <strong>40.15%</strong>
                    <div class="progress progress-xs mt-2">
                        <div class="progress-bar" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
  </div>
</div>

app/views/admins/topics/_topic.html.erb
<%- cache do%>
  <tr>
    <td><%= topic.id%></td>
    <td><%= topic.title%></td>
    <td><%= topic.user.email%></td>
    <td><%= l(topic.created_at, format: :long)%></td>
    <td><%= topic.disply_status%></td>
    <td><a>不通过</a></td>
  </tr>
<% end -%>

app/views/admins/topics/index.html.erb
<div class="container-fluid">
  <div class="animated fadeIn">
    <div class="row">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>标题</th>
            <th>发帖人</th>
            <th>帖子状态</th>
            <th>发帖时间</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <%= render @topics%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<%content_for :notice do%>
  <%= render "shared/notice", messages: flash[:notice] , notice: 'success'%>
<%end if flash[:notice].present?%>

<h2>this is a home page</h2>

app/views/layouts/_admin_nav.html.erb
<header class="app-header navbar">
  <a class="navbar-brand" href="#"></a>
  <ul class="nav navbar-nav d-md-down-none">
    <li class="nav-item px-3">
      <%= link_to("看板",  admins_home_index_path, class: "nav-link")%>
    </li>
    <li class="nav-item px-3">
      <%= link_to("帖子管理",  admins_topics_path, class: "nav-link")%>
    </li>
    <li class="nav-item px-3">
      <a class="nav-link" href="#">Settings</a>
    </li>
  </ul>
  <ul class="nav navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <span class="d-md-down-none">admin</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-header text-center">
          <strong>账号</strong>
        </div>
        <%= link_to('退出',
          { controller: 'admins/sessions', action: 'destroy'},
          { :method => :DELETE, :class => 'dropdown-item'}
        ) %>
      </div>
    </li>
  </ul>
  <button class="navbar-toggler aside-menu-toggler" type="button">☰</button>
</header>

app/views/layouts/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
  <h5 class="my-0 mr-md-auto font-weight-normal home-navbar-brand"></h5>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to(welcome_path, class: "p-2 text-dark") do%>
      首页 <span class="sr-only">(current)</span>
    <% end %>
    <%= link_to(topics_path, class: "p-2 text-dark") do %>
      活动区<span class="sr-only">(current)</span>
    <%- end%>
    <a class="p-2 text-dark" href="#">Support</a>
    <a class="p-2 text-dark" href="#">Pricing</a>
  </nav>
  <%- if user_signed_in? %>
  <ul>
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">个人中心</a>
      <div class="dropdown-menu">
        <%= link_to("个人资料", "#", class:"dropdown-item")%>
        <%= link_to("推广活动记录", "#", class:"dropdown-item")%>
        <%= link_to("推广产品记录", "#", class:"dropdown-item")%>
        <%= link_to('退出',
          { controller: 'devise/sessions', action: 'destroy'},
          { :method => :DELETE, :class => 'dropdown-item'}
        ) %>
      </div>
    </li>
    </ul>
  <% else %>
    <%=link_to('登录', new_user_session_path, class: 'btn btn-link')%>
    <%=link_to('注册', new_user_registration_path, class: 'btn btn-link')%>
  <% end -%>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="cn">
  <head>
    <title>圈子</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'admins/simple-line-icons', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_link_tag 'admins/style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">
    <%- if admin_signed_in? %>
      <%= render "layouts/admin_nav"%>
      <div class="app-body">
        <%=yield %>
      </div>
    <%else%>
      <div class="container">
        <%=yield %>
      </div>
    <% end -%>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="cn">
  <head>
    <title>圈子</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body id="dummybodyid">
    <%=render "layouts/nav" %>
    <div class="container">
      <%= yield :notice%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_login.html.erb
<%= form_for(resource, as: resource_name, url: session_path(resource_name), html:{class: "form-signin"}) do |f| %>
  <%content_for :notice do%>
    <%= render "shared/notice", messages: [flash[:alert]], notice: 'failure'%>
  <%end if flash[:alert]%>
  <h2 class="form-signin-heading">登 录</h2>
  <label for="inputEmail" class="sr-only">Email address</label>
  <%= f.email_field :email, placeholder: "邮箱", autocomplete: "off", class: "form-control", required: "required" %>
  <label for="inputPassword" class="sr-only">Password</label>
  <%= f.password_field :password, placeholder: "密码", autocomplete: "off", class: "form-control", required: "required"%>
  <div class="checkbox">
    <label>
      <%= f.check_box :remember_me %> 记住我
    </label>
  </div>
  <div class="actions">
    <%= f.submit "登录", class: 'btn btn-lg btn-primary btn-block' %>
  </div>
<% end %>

app/views/shared/_notice.html.erb
<%- if notice == "failure"%>
  <div class="alert alert-danger alert-dismissible fade show mt-md-3" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%messages.each do |msg|%>
      <%=msg.gsub!(" ", '')%><br>
    <% end -%>
  </div>
<%else%>
  <div class="alert alert-success alert-dismissible fade show mt-md-3" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
     <%= messages%>
  </div>
<%end-%>

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :topic_user_id %>
  </div>

  <div class="field">
    <%= form.label :company_link %>
    <%= form.text_field :company_link, id: :topic_company_link %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :topic_content %>
  </div>

  <div class="field">
    <%= form.label :String %>
    <%= form.text_field :String, id: :topic_String %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :topic_title %>
  </div>

  <div class="field">
    <%= form.label :tag %>
    <%= form.text_field :tag, id: :topic_tag %>
  </div>

  <div class="field">
    <%= form.label :String %>
    <%= form.text_field :String, id: :topic_String %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<div class="card-deck mb-3 text-center">
  <% 4.times do%>
    <div class="card mb-4 box-shadow">
      <img class="card-img-top" data-src="holder.js/100px180/" alt="100%x180" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22244%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20244%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16922e2be3b%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A12pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16922e2be3b%22%3E%3Crect%20width%3D%22244%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2291.3046875%22%20y%3D%2295.55%22%3E244x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="height: 180px; width: 100%; display: block;">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  <%- end%>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @topic.user_id %>
</p>

<p>
  <strong>Company link:</strong>
  <%= @topic.company_link %>
</p>

<p>
  <strong>Content:</strong>
  <%= @topic.content %>
</p>

<p>
  <strong>String:</strong>
  <%= @topic.String %>
</p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @topic.tag %>
</p>

<p>
  <strong>String:</strong>
  <%= @topic.String %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>